//! `.tomo/README.md` — the agent-context file (decided 2026-07-21).
//!
//! A mostly-static, version-stamped markdown file written into `.tomo/` on both
//! machines. Because `.tomo/**` is hardcoded-ignored (CLAUDE.md invariant #1) it
//! never syncs — each side generates its own copy, with side-specific content
//! (the serving binary's path and the live peer identity differ per machine).
//!
//! It is addressed to a *coding agent* working in a synced tree: it explains
//! that files can change under it at any moment, that its own edits propagate
//! instantly, and — the killer fact — that every save is versioned so nothing is
//! ever lost. tomo deliberately never writes to the user's own `CLAUDE.md` /
//! `AGENTS.md`; it only offers a snippet to paste.
//!
//! Everything here is pure and unit-testable: [`render_readme`] substitutes a
//! handful of placeholders into [`TEMPLATE`], and [`should_write`] decides
//! whether an existing file needs (re)writing purely from its template-version
//! marker. The I/O wrapper [`write_if_needed`] is the only impure part, and it is
//! best-effort — a failure to write the README must never abort a sync.

use crate::error::CliError;
use crate::layout::Layout;

/// The template-version marker stamped into the file. Bump the version suffix
/// whenever [`TEMPLATE`]'s content changes so existing files are regenerated on
/// upgrade (see [`should_write`]). It must appear verbatim in [`TEMPLATE`].
pub const README_MARKER: &str = "<!-- tomo-readme-v1 -->";

/// Which end of the sync pair this README describes. Only the wording of one
/// line differs; the substance is identical.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Side {
    /// The machine that ran `tomo sync` (or `tomo init`) — the initiator.
    Initiator,
    /// The machine running `tomo serve` (the bootstrapped remote).
    Serving,
}

impl Side {
    /// A short human label used in the "generated for the … side" line.
    fn label(self) -> &'static str {
        match self {
            Side::Initiator => "initiating",
            Side::Serving => "serving",
        }
    }
}

/// Everything [`render_readme`] needs to fill the template. Plain data so the
/// render is a pure function of its inputs.
#[derive(Debug, Clone)]
pub struct ReadmeContext {
    /// The tomo version that generated the file (display only; the *template*
    /// version lives in [`README_MARKER`]).
    pub tomo_version: String,
    /// The literal path to the binary that serves this project. On a
    /// bootstrapped remote this is the pushed `…/.tomo/bin/tomo-<ver>-<triple>`
    /// (from `current_exe`, which is not on `PATH`); on the initiator it is the
    /// invoked binary's path, falling back to plain `tomo`.
    pub binary_path: String,
    /// Which side this file describes.
    pub side: Side,
    /// The peer's name (hostname), if cheaply known at write time.
    pub peer_name: Option<String>,
    /// The peer's address, if cheaply known at write time.
    pub peer_addr: Option<String>,
}

impl ReadmeContext {
    /// The inline "peer as of the last (re)write" fragment. Points at the live
    /// data when the name is not yet known at write time.
    fn peer_line(&self) -> String {
        match (&self.peer_name, &self.peer_addr) {
            (Some(name), Some(addr)) => format!("{name} ({addr})"),
            (Some(name), None) => name.clone(),
            (None, Some(addr)) => addr.clone(),
            (None, None) => "not yet known — see `.tomo/state/status.json`".to_owned(),
        }
    }
}

/// The static template. Placeholders (`{{…}}`) are substituted by
/// [`render_readme`]; `{{TOMO}}` (the binary path) may occur several times.
const TEMPLATE: &str = r#"<!-- tomo-readme-v1 -->
# You're in a tomo-synced tree

This directory is kept in real-time, two-way sync with a peer machine by
**tomo**. Every file here is mirrored to the other machine over SSH within
milliseconds of each save, and every save is captured in a local history.

`.tomo/` is tomo's state directory — history database, staging area, config,
and this file. Never edit, sync, commit, or delete anything inside it. (It
can't sync itself: tomo hard-ignores `.tomo/**`.)

_Generated by tomo {{VERSION}} for the {{SIDE}} side of this pair. Peer as of
the last (re)write: {{PEER}}._

## Files here change on their own

A human or agent on the peer machine can edit any file, and tomo applies the
change here within milliseconds — nothing you did triggered it.

- **Re-read before you edit.** A file you read a minute ago may already be
  different on disk. Don't act on a stale read.
- **Don't "fix" changes you didn't make.** A diff you didn't write is almost
  certainly the peer's work arriving, not corruption — reverting it fights a
  live person on the other end.

## Your edits leave immediately

Every save you make shows up on the peer right away, including half-finished
files mid-refactor. There is no publish step.

## The safety net: nothing is ever lost

Every save of every file becomes a version. If the peer overwrites your work,
get it back:

    {{TOMO}} log <path>                 # list a file's versions
    {{TOMO}} restore <path> --version <n>

Conflicts never block sync. When both sides change one file concurrently, a
single deterministic winner lands on disk and the loser is preserved in
history — `{{TOMO}} conflicts` lists them. You never have to stop and merge.

## What does NOT sync

tomo skips machine-local, regenerable trees by default: `node_modules`,
`.venv`/`venv`, `__pycache__`, `.terraform`, `.git`, IDE dirs (`.idea`,
`.vscode`, …), and editor temp files. So a local `npm install` or `pip
install` staying local is expected, not a bug — re-run it on each machine.

## Who's on the other end

The live peer, connection state, and session pid:

    cat .tomo/state/status.json      # the "peer" and "connected" fields
    {{TOMO}} status --json

## Don't kill the sync process

The running `tomo sync` (or `tomo serve`) process is deliberate — it IS the
sync. When you clean up stray processes, leave it alone.

## Tell your own instructions file

tomo will not touch your CLAUDE.md / AGENTS.md. If you keep one, consider
adding a line like:

> This project syncs in real time with a peer machine via tomo — see
> `.tomo/README.md`. Files may change without my action; re-read before
> editing, and don't revert changes I didn't make.
"#;

/// Render the agent-context README for `ctx`. Pure: the same context always
/// yields the same bytes.
#[must_use]
pub fn render_readme(ctx: &ReadmeContext) -> String {
    TEMPLATE
        .replace("{{VERSION}}", &ctx.tomo_version)
        .replace("{{SIDE}}", ctx.side.label())
        .replace("{{PEER}}", &ctx.peer_line())
        .replace("{{TOMO}}", &ctx.binary_path)
}

/// Decide whether the README should be (re)written, given the current file's
/// contents (`None` when the file is absent).
///
/// Purely marker-driven, so it is cheap and churn-free:
/// - absent → write;
/// - present but the current [`README_MARKER`] is **not** found (an older
///   template version, or a hand-mangled/garbage file that lost the marker) →
///   rewrite;
/// - present and the current marker is found → skip, even if a human edited the
///   prose around it (documented: we never clobber a file already carrying this
///   template version).
#[must_use]
pub fn should_write(existing: Option<&str>) -> bool {
    match existing {
        None => true,
        Some(text) => !text.contains(README_MARKER),
    }
}

/// Write `.tomo/README.md` for `ctx` if [`should_write`] says so. Returns
/// `Ok(true)` when it wrote, `Ok(false)` when it left an up-to-date file
/// untouched.
///
/// # Errors
/// [`CliError::Io`] if the file exists but cannot be read, or cannot be written.
/// Callers treat any error as non-fatal — syncing matters more than the README.
pub fn write_if_needed(layout: &Layout, ctx: &ReadmeContext) -> Result<bool, CliError> {
    let path = readme_path(layout);
    let existing = match std::fs::read_to_string(&path) {
        Ok(text) => Some(text),
        Err(err) if err.kind() == std::io::ErrorKind::NotFound => None,
        Err(source) => return Err(CliError::io("read .tomo/README.md", &path, source)),
    };
    if !should_write(existing.as_deref()) {
        return Ok(false);
    }
    let body = render_readme(ctx);
    std::fs::write(&path, body).map_err(|s| CliError::io("write .tomo/README.md", &path, s))?;
    Ok(true)
}

/// `.tomo/README.md` for `layout`.
fn readme_path(layout: &Layout) -> std::path::PathBuf {
    layout.tomo().join("README.md")
}

/// The path to the currently-running binary as a display string, or the plain
/// command name `tomo` when it cannot be determined (best-effort, per the
/// design: the initiator falls back to `tomo`).
#[must_use]
pub fn current_binary_path() -> String {
    std::env::current_exe().map_or_else(|_| "tomo".to_owned(), |p| p.to_string_lossy().into_owned())
}

/// Best-effort convenience used by `tomo init` (no session, so no peer yet):
/// write the initiator-side README with the invoked binary's path.
///
/// # Errors
/// As for [`write_if_needed`].
pub fn write_default(layout: &Layout, tomo_version: &str) -> Result<bool, CliError> {
    let ctx = ReadmeContext {
        tomo_version: tomo_version.to_owned(),
        binary_path: current_binary_path(),
        side: Side::Initiator,
        peer_name: None,
        peer_addr: None,
    };
    write_if_needed(layout, &ctx)
}

/// Whether `text` carries the current template-version marker (test helper).
#[cfg(test)]
fn contains_marker(text: &str) -> bool {
    text.contains(README_MARKER)
}

#[cfg(test)]
#[allow(clippy::unwrap_used, clippy::expect_used)]
mod tests {
    use super::*;

    fn ctx() -> ReadmeContext {
        ReadmeContext {
            tomo_version: "0.1.12".to_owned(),
            binary_path: "/srv/proj/.tomo/bin/tomo-0.1.12-x86_64-unknown-linux-musl".to_owned(),
            side: Side::Serving,
            peer_name: Some("jakes-mbp".to_owned()),
            peer_addr: Some("203.0.113.7".to_owned()),
        }
    }

    #[test]
    fn render_substitutes_every_placeholder() {
        let out = render_readme(&ctx());
        // No template token survives.
        assert!(!out.contains("{{"), "unsubstituted placeholder in:\n{out}");
        // Each value is present.
        assert!(out.contains("0.1.12"));
        assert!(out.contains("/srv/proj/.tomo/bin/tomo-0.1.12-x86_64-unknown-linux-musl"));
        assert!(out.contains("serving"));
        assert!(out.contains("jakes-mbp (203.0.113.7)"));
        // The binary path substitutes into every command occurrence (log,
        // restore, conflicts, status → at least four).
        let occurrences = out.matches(&ctx().binary_path).count();
        assert!(occurrences >= 4, "binary path only appeared {occurrences}×");
    }

    #[test]
    fn render_has_natural_quotes() {
        let out = render_readme(&ctx());
        assert!(!out.contains("\"\""), "doubled quotes leaked into output");
        assert!(out.contains("\"fix\""));
        assert!(out.contains("\"peer\""));
    }

    #[test]
    fn render_carries_the_marker() {
        assert!(contains_marker(&render_readme(&ctx())));
        // The marker is on the very first line so a cheap head-read finds it.
        assert!(render_readme(&ctx()).starts_with(README_MARKER));
    }

    #[test]
    fn render_is_well_under_100_lines() {
        let n = render_readme(&ctx()).lines().count();
        assert!(n < 100, "README is {n} lines — trim it back under 100");
    }

    #[test]
    fn render_is_deterministic() {
        assert_eq!(render_readme(&ctx()), render_readme(&ctx()));
    }

    #[test]
    fn peer_line_falls_back_when_unknown() {
        let mut c = ctx();
        c.peer_name = None;
        c.peer_addr = None;
        let out = render_readme(&c);
        assert!(out.contains("not yet known"));
    }

    #[test]
    fn peer_line_name_only() {
        let mut c = ctx();
        c.peer_addr = None;
        assert_eq!(c.peer_line(), "jakes-mbp");
    }

    #[test]
    fn side_wording_differs() {
        let mut c = ctx();
        c.side = Side::Initiator;
        assert!(render_readme(&c).contains("initiating"));
    }

    // ---- rewrite decision -------------------------------------------------

    #[test]
    fn write_when_absent() {
        assert!(should_write(None));
    }

    #[test]
    fn skip_when_current_marker_present() {
        let rendered = render_readme(&ctx());
        assert!(!should_write(Some(&rendered)));
    }

    #[test]
    fn skip_user_modified_file_that_keeps_the_marker() {
        // A human added a note but left the marker line intact → still skipped.
        let mut doc = render_readme(&ctx());
        doc.push_str("\n\n> my own note\n");
        assert!(!should_write(Some(&doc)));
    }

    #[test]
    fn rewrite_when_marker_is_an_older_version() {
        let old = "<!-- tomo-readme-v0 -->\n# an older README\n";
        assert!(should_write(Some(old)));
    }

    #[test]
    fn rewrite_garbage_without_any_marker() {
        assert!(should_write(Some("just some unrelated text\n")));
        assert!(should_write(Some("")));
    }
}
