//! Where the bytes to push to a remote come from (docs/SPEC.md §3, cross-release
//! skill).
//!
//! Two sources, tried in order:
//!
//! 1. **Embedded release binaries** (M6). A *fat* build — compiled with the
//!    `embed-binaries` feature — carries a static musl (and, when built, darwin)
//!    binary for every supported triple, generated at build time by `build.rs`
//!    from `$TOMO_EMBED_DIR` (see [`crate::binary_for_triple`]). The bootstrap
//!    serves the embedded bytes matching the remote triple **and the exact local
//!    version**, first. A triple we did not embed is a clean
//!    [`TransportError::UnsupportedTarget`] listing what *is* embedded — never a
//!    download.
//! 2. **Dev-mode self substitution** (loud, debug-only allowance). Development
//!    builds on this Linux VM are `x86_64-unknown-linux-gnu`, but a Linux remote
//!    is detected as `x86_64-unknown-linux-musl` (SPEC §3 mandates musl for
//!    release). So that localhost end-to-end scenarios can exercise the real
//!    bootstrap without embedding real 40 MB binaries, a *non-embedded*,
//!    *non-release* build may satisfy a musl request with its own gnu
//!    `current_exe` **when the architecture and OS match**. [`plan_binary`]
//!    refuses the substitution in release builds (`dev_build == false`); the CLI
//!    prints a conspicuous warning whenever [`BinarySource::dev_substitution`] is
//!    set. This path is taken only when nothing is embedded.
//!
//! The [`plan_binary`] decision and the [`select_embedded`] lookup are pure and
//! unit-tested in isolation; the `current_exe` read and the real embedded table
//! live behind them.

use crate::error::TransportError;
use crate::triple;

/// One release binary embedded into a *fat* build: the triple it runs on, the
/// exact version it was built at, and its bytes.
///
/// The real table is generated by `build.rs` (only under the `embed-binaries`
/// feature) from the artifacts in `$TOMO_EMBED_DIR`; in an ordinary dev build
/// the table is empty. The type is public-in-crate so tests can build fixture
/// tables without any real artifacts.
pub(crate) struct EmbeddedBinary {
    /// The target triple this binary runs on.
    pub triple: &'static str,
    /// The exact version string it was built at (`tomo-<version>-<triple>`).
    pub version: &'static str,
    /// The binary's bytes.
    pub bytes: &'static [u8],
}

// The generated table, present only in a fat build. `build.rs` writes an
// `EMBEDDED` slice into `$OUT_DIR/embedded.rs`; it references `EmbeddedBinary`
// from this module.
#[cfg(feature = "embed-binaries")]
mod generated {
    use super::EmbeddedBinary;
    include!(concat!(env!("OUT_DIR"), "/embedded.rs"));
}

/// The binaries embedded in this build. Empty unless compiled with
/// `--features embed-binaries` and `$TOMO_EMBED_DIR` populated at build time.
fn embedded_table() -> &'static [EmbeddedBinary] {
    #[cfg(feature = "embed-binaries")]
    {
        generated::EMBEDDED
    }
    #[cfg(not(feature = "embed-binaries"))]
    {
        &[]
    }
}

/// Pure lookup: the embedded binary whose triple **and** version match exactly.
///
/// Exact-version matching honors SPEC §3 ("exact version match or re-push — no
/// ranges, no 'close enough'").
fn select_embedded<'a>(
    table: &'a [EmbeddedBinary],
    requested: &str,
    version: &str,
) -> Option<&'a EmbeddedBinary> {
    table
        .iter()
        .find(|e| e.triple == requested && e.version == version)
}

/// The distinct triples present in `table`, comma-separated, for an
/// [`TransportError::UnsupportedTarget`] message. `"(none embedded)"` if empty.
fn embedded_triples(table: &[EmbeddedBinary]) -> String {
    if table.is_empty() {
        return "(none embedded)".to_owned();
    }
    let mut names: Vec<&str> = table.iter().map(|e| e.triple).collect();
    names.sort_unstable();
    names.dedup();
    names.join(", ")
}

/// The inventory of binaries embedded in this build: `(triple, version, bytes)`.
///
/// Empty unless built with `--features embed-binaries`. Surfaced by the hidden
/// `tomo dev embedded-binaries` diagnostic so a fat binary can report exactly
/// what it will push (used by `scripts/release.sh` verification).
pub fn embedded_inventory() -> Vec<(&'static str, &'static str, usize)> {
    embedded_table()
        .iter()
        .map(|e| (e.triple, e.version, e.bytes.len()))
        .collect()
}

/// A resolved binary ready to push: which triple it is *for* and its bytes.
#[derive(Debug, Clone)]
pub struct BinarySource {
    /// The remote triple this binary will be named for.
    pub triple: String,
    /// The binary's bytes (embedded release artifact, or `current_exe` in dev).
    pub bytes: Vec<u8>,
    /// Whether these bytes came from an embedded release artifact (a fat build)
    /// rather than the running executable.
    pub embedded: bool,
    /// Whether this is the debug-only cross-runtime substitution (gnu binary
    /// serving a musl request); the CLI warns loudly when true.
    pub dev_substitution: bool,
}

/// The pure decision behind [`binary_for_triple`]: given the remote's requested
/// triple, the triple we were built for, and whether this is a dev build, may
/// we push our own `current_exe`, and is it a substitution?
///
/// # Errors
/// [`TransportError::UnsupportedTarget`] when we have no bytes for `requested`.
pub fn plan_binary(
    requested: &str,
    built_for: &str,
    dev_build: bool,
) -> Result<BinaryPlan, TransportError> {
    if requested == built_for {
        return Ok(BinaryPlan {
            dev_substitution: false,
        });
    }
    // Dev-only allowance: same arch+OS, different C runtime (gnu vs musl).
    if dev_build && triple::arch_os(requested) == triple::arch_os(built_for) {
        return Ok(BinaryPlan {
            dev_substitution: true,
        });
    }
    Err(TransportError::UnsupportedTarget {
        detected: requested.to_owned(),
        supported: triple::supported_list(),
    })
}

/// The outcome of [`plan_binary`]: we can serve `current_exe`, possibly as a
/// dev substitution. (M6 will add an `Embedded(triple)` variant.)
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct BinaryPlan {
    /// Whether this is the debug-only gnu-for-musl substitution.
    pub dev_substitution: bool,
}

/// Resolve the bytes to push for `requested` at `version`.
///
/// Embedded release artifacts win: in a fat build (`embed-binaries` feature) the
/// exact triple+version match is served first, and a triple we did not embed is
/// a clean [`TransportError::UnsupportedTarget`] listing what *is* embedded — no
/// fallback, no download. Only a non-embedded (dev) build reaches the
/// `current_exe` substitution path, gated by `dev_build` and `built_for` (the
/// triple this binary was compiled for, supplied by the CLI from its
/// `build.rs`).
///
/// # Errors
/// [`TransportError::UnsupportedTarget`] if we have no matching binary, or
/// [`TransportError::LocalBinary`] if `current_exe` cannot be read.
pub fn binary_for_triple(
    requested: &str,
    built_for: &str,
    version: &str,
    dev_build: bool,
) -> Result<BinarySource, TransportError> {
    let table = embedded_table();

    // 1. Embedded release artifact — exact triple + version match, served first.
    if let Some(embedded) = select_embedded(table, requested, version) {
        return Ok(BinarySource {
            triple: requested.to_owned(),
            bytes: embedded.bytes.to_vec(),
            embedded: true,
            dev_substitution: false,
        });
    }

    // 2. In a fat build we never fall back to `current_exe`: a triple we did not
    //    embed is a clean, explicit error naming what we *do* have.
    if cfg!(feature = "embed-binaries") {
        return Err(TransportError::UnsupportedTarget {
            detected: requested.to_owned(),
            supported: embedded_triples(table),
        });
    }

    // 3. Dev build (nothing embedded): the debug-only `current_exe` path.
    let plan = plan_binary(requested, built_for, dev_build)?;
    let exe = std::env::current_exe().map_err(|e| TransportError::LocalBinary {
        reason: format!("cannot locate current executable: {e}"),
    })?;
    let bytes = std::fs::read(&exe).map_err(|e| TransportError::LocalBinary {
        reason: format!("cannot read {}: {e}", exe.display()),
    })?;
    Ok(BinarySource {
        triple: requested.to_owned(),
        bytes,
        embedded: false,
        dev_substitution: plan.dev_substitution,
    })
}

#[cfg(test)]
#[allow(clippy::unwrap_used, clippy::expect_used)]
mod tests {
    use super::*;

    #[test]
    fn exact_match_no_substitution() {
        let plan =
            plan_binary(triple::X86_64_LINUX_MUSL, triple::X86_64_LINUX_MUSL, false).unwrap();
        assert!(!plan.dev_substitution);
    }

    #[test]
    fn dev_gnu_serves_musl() {
        let plan =
            plan_binary(triple::X86_64_LINUX_MUSL, "x86_64-unknown-linux-gnu", true).unwrap();
        assert!(plan.dev_substitution);
    }

    #[test]
    fn release_gnu_refuses_musl() {
        let err =
            plan_binary(triple::X86_64_LINUX_MUSL, "x86_64-unknown-linux-gnu", false).unwrap_err();
        assert!(matches!(err, TransportError::UnsupportedTarget { .. }));
    }

    #[test]
    fn different_arch_always_refused() {
        assert!(plan_binary(triple::AARCH64_LINUX_MUSL, "x86_64-unknown-linux-gnu", true).is_err());
    }

    #[test]
    fn different_os_refused() {
        assert!(plan_binary(triple::X86_64_DARWIN, "x86_64-unknown-linux-gnu", true).is_err());
    }

    // --- embedded-lookup logic (pure; fixture tables, no real artifacts) -----

    fn fixture_table() -> Vec<EmbeddedBinary> {
        vec![
            EmbeddedBinary {
                triple: triple::X86_64_LINUX_MUSL,
                version: "0.0.1",
                bytes: b"x86-musl-bytes",
            },
            EmbeddedBinary {
                triple: triple::AARCH64_LINUX_MUSL,
                version: "0.0.1",
                bytes: b"aarch64-musl-bytes",
            },
        ]
    }

    #[test]
    fn embedded_exact_triple_and_version_matches() {
        let table = fixture_table();
        let hit = select_embedded(&table, triple::X86_64_LINUX_MUSL, "0.0.1")
            .expect("exact match present");
        assert_eq!(hit.bytes, b"x86-musl-bytes");
    }

    #[test]
    fn embedded_version_mismatch_is_no_match() {
        let table = fixture_table();
        // Right triple, wrong version → no "close enough"; must miss (SPEC §3).
        assert!(select_embedded(&table, triple::X86_64_LINUX_MUSL, "0.0.2").is_none());
    }

    #[test]
    fn embedded_absent_triple_is_no_match() {
        let table = fixture_table();
        assert!(select_embedded(&table, triple::X86_64_DARWIN, "0.0.1").is_none());
    }

    #[test]
    fn embedded_triples_lists_available_sorted_and_deduped() {
        let table = fixture_table();
        assert_eq!(
            embedded_triples(&table),
            format!(
                "{}, {}",
                triple::AARCH64_LINUX_MUSL,
                triple::X86_64_LINUX_MUSL
            )
        );
        assert_eq!(embedded_triples(&[]), "(none embedded)");
    }
}
